#162948887 Users should be able to see time it takes to read an article
andela/ah-alpha-frontend pull request #24
Opened 2019-02-26 12:53 UTC by Ruiru11

#### What does this PR do?
* Implement read time on articles

#### Description of Task to be completed?
* Enable users to see the time it takes to read an article

#### How should this be manually tested?
* Clone the github repository `git clone https://github.com/andela/ah-alpha-frontend` on your local machine.
* run `git checkout ft-readtime-162948887`
* Install the required dependencies using `npm install`
* Run the local development server using `npm start`

#### Screenshot (on viewing all articles)
![image](https://user-images.githubusercontent.com/36441430/53413809-20f59880-39de-11e9-84af-cf5612136377.png)

#### Screenshot (on viewing a single article)
![image](https://user-images.githubusercontent.com/36441430/53413869-50a4a080-39de-11e9-9651-0ea61a6a9ee2.png)

#### What are the relevant pivotal tracker stories?
[#162948887](https://www.pivotaltracker.com/story/show/162948887)

2019-02-26 13:00 UTC, tesh254 commented on src/components/containers/articles/Articles.js
> +                                <span className="read">{article.read_time.substr(3, 1)} min read</span>
Format this to take up multiple lines

2019-02-26 13:00 UTC, tesh254 commented on src/components/containers/articles/OneArticle.js
> +                  <span className="read-time"> {moment(article.created_at).format("MMM Do")}</span><br />
Also this anyway it looks good

2019-02-26 15:29 UTC, tesh254 approved these changes

2019-02-27 06:19 UTC, boltonotieno requested changes
Nice on work on the implementation. However, from your screenshots,  the same way you've displayed the read time on the articles card `2 min read `, you could do the same on the single article page instead of `2 min` without the `read ` word

2019-02-27 06:22 UTC, Ruiru11 commented
> Nice on work on the implementation. However, from your screenshots, the same way you've displayed the read time on the articles card `2 min read `, you could do the same on the single article page instead of `2 min` without the `read ` word

(the fast implementation was as you are requesting but the PO said we should do away with the `read`)

2019-02-27 06:30 UTC, BoltC0rt3z commented
> > Nice on work on the implementation. However, from your screenshots, the same way you've displayed the read time on the articles card `2 min read `, you could do the same on the single article page instead of `2 min` without the `read ` word
> 
> (the fast implementation was as you are requesting but the PO said we should do away with the `read`)

Ooh, that's okay.

2019-02-27 06:30 UTC, boltonotieno approved these changes

2019-02-27 06:58 UTC, danuluma commented on src/components/containers/articles/OneArticle.js
> +                  <br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
This could be padded better using css

2019-02-27 06:58 UTC, danuluma approved these changes
Nice work

2019-02-27 07:46 UTC, merged